### ISSUE TITLE
Testing simple HTML responses

### ISSUE THREAD

**Issue by vabue** [zatosource/zato-apitest#38]
Some weird apis give HTML, not JSON/XML. If I try to test them xpath doesn't work. 

Example on the default Nginx setup:

```
  Scenario: Nginx is working
    Given address "http://nginx.local"
    Given URL path "/"
    Given HTTP method "GET"
    When the URL is invoked
    Then status is "200"
    And header "Server" contains "nginx"
    And XPath "/html/body/h1" isn't empty
      Traceback (most recent call last):
        File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 1173, in run
          match.run(runner.context)
        File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 1589, in run
          self.func(context, *args, **kwargs)
        File "/usr/local/lib/python2.7/dist-packages/zato/apitest/steps/xml.py", line 45, in inner
          elem = data_impl.xpath(xpath, namespaces=ctx.zato.request.ns_map)
      AttributeError: 'unicode' object has no attribute 'xpath'

      Captured logging:
      INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): nginx.local
```

**Comment by dsuch** [comment]
Mass-closing old tickets.
