### ISSUE TITLE
Environment variables in Basic Auth step doesn't work

### ISSUE THREAD

**Issue by vabue** [zatosource/zato-apitest#40]
Usage of the feature's environment variables is documented as:

```
    Given address "$MYAPP_ADDRESS"
```

But if we use native Basic Auth step, putting variable generates error:

```
   Given Basic Auth "$LOGIN_YT11" "$PASSWORD_YT11"
      Traceback (most recent call last):
        File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 1173, in run
          match.run(runner.context)
        File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 1589, in run
          self.func(context, *args, **kwargs)
        File "/usr/local/lib/python2.7/dist-packages/zato/apitest/util.py", line 70, in inner
          kwargs[kwarg] = config_func(ctx, value[1:])
        File "/usr/local/lib/python2.7/dist-packages/zato/apitest/util.py", line 47, in get_value_from_environ
          return os.environ[name]
        File "/usr/lib/python2.7/UserDict.py", line 23, in __getitem__
          raise KeyError(key)
      KeyError: u'LOGIN_YT11'

    When the URL is invoked
    Then status is "200"
```

But if we omit brackets, test simply fails because of auth:

```
  Scenario: Important metadata is accessable
    Given address "@proxy_address"
    Given URL path "/yt11/odata/standard.odata"
    Given Basic Auth $LOGIN_YT11 $PASSWORD_YT11
    When the URL is invoked
    Then status is "200"
```

**Comment by dsuch** [comment]
Mass-closing old tickets.
