### ISSUE TITLE
Unable to perform API Call with 'application/merge-patch+json' Content-Type 

### ISSUE THREAD

**Issue by taimoorpashanbs17** [zatosource/zato-apitest#48]
I am trying using one call with 'PATCH' method, which uses 'application/merge-patch+json' content-type, while running it, console shows me following message:

`Traceback (most recent call last):
        File "/usr/local/lib/python2.7/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/usr/local/lib/python2.7/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "/usr/local/lib/python2.7/site-packages/zato/apitest/steps/common.py", line 57, in when_the_url_is_invoked
          invoke_http(ctx, adapters)
        File "/usr/local/lib/python2.7/site-packages/zato/apitest/steps/common.py", line 118, in invoke_http
          method, '{}{}{}'.format(address, url_path, qs), data=data, files=files, headers=ctx.zato.request.headers, auth=auth)
        File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 530, in request
          resp = self.send(prep, **send_kwargs)
        File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 643, in send
          r = adapter.send(request, **kwargs)
        File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
          raise ConnectionError(e, request=request)

requests.exceptions.ConnectionError: HTTPConnectionPool(host='my hostname', port=80): Max retries exceeded with url: end_point (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f844ae482d0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))`

I am pretty much sure that it is causing due to Content type , as I view your code that it is not handling that type on `invoke_http `method on `common.py` script.

**Comment by dsuch** [comment]
> requests.exceptions.ConnectionError: HTTPConnectionPool(host='my hostname', port=80): Max retries exceeded with url: end_point (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f844ae482d0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))`

Hello @taimoorpashanbs17,

can you please explain what kind of a special treatment of "application/merge-patch+json" you would like to see?

Also, have you analysed this traceback? It says "[Errno -2] Name does not resolve".

**Comment by taimoorpashanbs17** [comment]
Hello @dsuch 

I have ran same end point on postman, its running fine over there, and all end points are running fine. Except for those, which are having 'application/merge-patch+json'.

I am not asking any special treatment, just asking that I think one content-type can be added on your common.py file.

**Comment by dsuch** [comment]
Ok, but we have two aspects here:

* I really do not understand what you mean by adding it - what needs to be added and where? 
* You have an exception that  "[Errno -2] Name does not resolve" -> this is returned by your Linux system and is not related to API Test as such, have you looked it up in the Internet?

**Comment by taimoorpashanbs17** [comment]
Ok, So I am running all other API test on same Linux system, they are running fine..
Just two of the calls which requires content-type of this are not.
Also I am using Patch Method for this rather than 'PUT', as it is update end point.

**Comment by taimoorpashanbs17** [comment]
And by adding means that you add this content-type as well in your methods.
